import { Button } from '@mui/material';
import React, { useState } from 'react';

const SecurityConsultancy1 = [
  { label: "Splunk", color: "#7B7B7B" },
  { label: "IBM QRadar", color: "#7B7B7B" },
  { label: "ArcSight", color: "#7B7B7B" },
  { label: "LogRhythm", color: "#7B7B7B" },
  { label: "AlienVault", color: "#7B7B7B" },
  { label: "Graylog", color: "#7B7B7B" },
  { label: "Sentinel", color: "#7B7B7B" },
];
const SecurityConsultancy2 = [
  { label: "CrowdStrike Falcon", color: "#7B7B7B" },
  { label: "Carbon Black", color: "#7B7B7B" },
  { label: "Sentinel One", color: "#7B7B7B" },
  { label: "Microsoft Defender for Endpoint", color: "#7B7B7B" },
  { label: "Palo Alto Networks Cortex XDR", color: "#7B7B7B" },
  { label: "Sophos Intercept X", color: "#7B7B7B" },
];
const SecurityConsultancy3 = [
  { label: "Swimlane", color: "#7B7B7B" },
  { label: "IBM Resilient", color: "#7B7B7B" },
  { label: "Splunk Phantom", color: "#7B7B7B" },
  { label: "Rapid7 InsightIDR", color: "#7B7B7B" },
  { label: "ServiceNow Security Incident Response", color: "#7B7B7B" },
  { label: "Cortex XSOAR (formerly Demisto)", color: "#7B7B7B" },
];
const SecurityConsultancy4 = [
  { label: "Secureworks", color: "#7B7B7B" },
  { label: "IBM Managed Security Services", color: "#7B7B7B" },
  { label: "AT&T Cybersecurity", color: "#7B7B7B" },
  { label: "Palo Alto Networks Managed Detection ", color: "#7B7B7B" },
  { label: "CrowdStrike Falcon Complete", color: "#7B7B7B" },
  { label: "FireEye Managed Defense", color: "#7B7B7B" },
];

const SecurityOperation = () => {
  const [hoverIndex1, setHoverIndex1] = useState(null);
  const [hoverIndex2, setHoverIndex2] = useState(null);
  const [hoverIndex3, setHoverIndex3] = useState(null);
  const [hoverIndex4, setHoverIndex4] = useState(null);

  return (
    <div id="security-operation-center"  className='flex flex-col items-center justify-center'>
      <h4 className="tracking-[1px] font-[700] leading-[43px] py-28 lg:leading-[60px] text-[48px] lg:text-[65px] mt-[40px] lg:mt-[122px] text-[#000000]">
      Security Operation Center
      </h4>

      <div className='grid-cols-1 lg:grid-cols-2 grid mt-28 px-20'>
        <div className='px-20'>
          <img className='h-[225px] w-[234px]' src='/InformationSecurity/SecurityOperation1.png' />

          <h1 className='text-[#006CFC] text-[48px] font-[700] leading-[70px] mt-6 lg:mt-12'>
            SIEM
          </h1>
          <h2 className=' lg:text-[20px] 2xl:text-[21px] text-[#9fa6b6] mt-4 lg:mt-10'>
            Improve your security operations with our SIEM (Security Information and Event Management) solutions. We provide real-time analysis of security alerts generated by applications and network hardware. Our SIEM services enable quick investigation, analysis, and response to security incidents. Enhance your threat detection and compliance efforts with our powerful and scalable SIEM solutions.
          </h2>
          <div>
            {SecurityConsultancy1.map((button, index) => (
              <Button
                key={index}
                variant="contained"
                onMouseEnter={() => setHoverIndex1(index)}
                onMouseLeave={() => setHoverIndex1(null)}
                style={{
                  backgroundColor: hoverIndex1 === index ? "#006CFC" : "#FFFFFF",
                  color: hoverIndex1 === index ? "#FFFFFF" : button.color,
                  fontSize: "15px",
                  fontWeight: "600",
                  textTransform: "none",
                  marginTop: "20px",
                
                  paddingTop: "7px",
                  boxShadow: "none",
                  borderRadius: "35px",
                  border: `1px solid ${button.color}`,
                  marginRight: "10px"
                }}
              >
                {button.label}
              </Button>
            ))}
          </div>
        </div>
        <div className='px-20'>
          <img className='h-[225px] w-[234px]' src='/InformationSecurity/SecurityOperation2.png' />

          <h1 className='text-[#006CFC] text-[48px] font-[700] leading-[70px] mt-6 lg:mt-12'>
            EDR / XDR
          </h1>
          <h2 className=' lg:text-[20px] 2xl:text-[21px] text-[#9fa6b6] mt-4 lg:mt-10'>
            Detect and respond to advanced threats with our EDR (Endpoint Detection and Response) and XDR (Extended Detection and Response) solutions. Our services offer comprehensive visibility and protection across endpoint, network, and cloud environments. Leverage artificial intelligence and machine learning to identify and mitigate cyber threats. Stay ahead of attackers with our proactive and integrated approach to security.
          </h2>
          <div>
            {SecurityConsultancy2.map((button, index) => (
              <Button
                key={index}
                variant="contained"
                onMouseEnter={() => setHoverIndex2(index)}
                onMouseLeave={() => setHoverIndex2(null)}
                style={{
                  backgroundColor: hoverIndex2 === index ? "#006CFC" : "#FFFFFF",
                  color: hoverIndex2 === index ? "#FFFFFF" : button.color,
                  fontSize: "15px",
                  fontWeight: "600",
                  textTransform: "none",
                  marginTop: "20px",
                
                  paddingTop: "7px",
                  boxShadow: "none",
                  borderRadius: "35px",
                  border: `1px solid ${button.color}`,
                  marginRight: "10px"
                }}
              >
                {button.label}
              </Button>
            ))}
          </div>
        </div>
      </div>
      <div className='grid-cols-1 lg:grid-cols-2 grid mt-28 px-20'>
        <div className='px-20'>
          <img className='h-[225px] w-[234px]' src='/InformationSecurity/SecurityOperation3.png' />

          <h1 className='text-[#006CFC] text-[48px] font-[700] leading-[70px] mt-6 lg:mt-12'>
            Incident & Breach Response
          </h1>
          <h2 className=' lg:text-[20px] 2xl:text-[21px] text-[#9fa6b6] mt-4 lg:mt-10'>
            Minimize damage and recover quickly from security incidents with our expert incident response and breach services. Our dedicated team is prepared to help you manage and mitigate the impact of cyber incidents. We provide rapid response, thorough investigation, and effective remediation strategies. Protect your reputation and assets with our comprehensive solutions.
          </h2>
          <div>
            {SecurityConsultancy3.map((button, index) => (
              <Button
                key={index}
                variant="contained"
                onMouseEnter={() => setHoverIndex3(index)}
                onMouseLeave={() => setHoverIndex3(null)}
                style={{
                  backgroundColor: hoverIndex3 === index ? "#006CFC" : "#FFFFFF",
                  color: hoverIndex3 === index ? "#FFFFFF" : button.color,
                  fontSize: "15px",
                  fontWeight: "600",
                  textTransform: "none",
                  marginTop: "20px",
                
                  paddingTop: "7px",
                  boxShadow: "none",
                  borderRadius: "35px",
                  border: `1px solid ${button.color}`,
                  marginRight: "10px"
                }}
              >
                {button.label}
              </Button>
            ))}
          </div>
        </div>
        <div className='px-20'>
          <img className='h-[225px] w-[234px]' src='/InformationSecurity/SecurityOperation4.png' />

          <h1 className='text-[#006CFC] text-[48px] font-[700] leading-[70px] mt-6 lg:mt-12'>
            24x7 Monitoring
          </h1>
          <h2 className=' lg:text-[20px] 2xl:text-[21px] text-[#9fa6b6] mt-4 lg:mt-10'>
            Stay protected around the clock with our 24x7 monitoring services. Our Security Operations Center (SOC) provides continuous monitoring, threat detection, and incident response. We use advanced tools and techniques to identify potential security issues before they become critical. Trust us to keep your systems secure, day and night.
          </h2>
          <div>
            {SecurityConsultancy4.map((button, index) => (
              <Button
                key={index}
                variant="contained"
                onMouseEnter={() => setHoverIndex4(index)}
                onMouseLeave={() => setHoverIndex4(null)}
                style={{
                  backgroundColor: hoverIndex4 === index ? "#006CFC" : "#FFFFFF",
                  color: hoverIndex4 === index ? "#FFFFFF" : button.color,
                  fontSize: "15px",
                  fontWeight: "600",
                  textTransform: "none",
                  marginTop: "20px",
                
                  paddingTop: "7px",
                  boxShadow: "none",
                  borderRadius: "35px",
                  border: `1px solid ${button.color}`,
                  marginRight: "10px"
                }}
              >
                {button.label}
              </Button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default SecurityOperation;
