import React, { useEffect, useRef } from "react";

const ServicesSectionTwo = () => {
    return (
        <section class="ngt_pm_services info_operation_center">
            <div class="ngt_container">
                <h1 className="main_heading text-[#006CFC]">Security Operation Center</h1>
                <div class="ngt_row">
                    <div class="ngt_col-lg-6">
                        <div className="operation_box">
                            <div className="operation_content">
                                <img src="/InformationSecurity/SecurityOperation1.png" />
                                <div className="operation_line"></div>
                                <h2>SIEM</h2>
                                <p>Improve your security operations with our SIEM (Security Information and Event Management) solutions. We provide real-time analysis of security alerts generated by applications and network hardware. Our SIEM services enable quick investigation, analysis, and response to security incidents. Enhance your threat detection and compliance efforts with our powerful and scalable SIEM solutions.</p>
                            </div>
                            <div className="service_pills">
                                <ul>
                                    <li>Splunk</li>
                                    <li>IBM QRadar</li>
                                    <li>ArcSight</li>
                                    <li>LogRhythm</li>
                                    <li>AlienVault</li>
                                    <li>Graylog</li>
                                    <li>Sentinel</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="ngt_col-lg-6">
                        <div className="operation_box">
                            <div className="operation_content">
                                <img src="/InformationSecurity/SecurityOperation2.png" />
                                <div className="operation_line"></div>
                                <h2>EDR / XDR </h2>
                                <p>Detect and respond to advanced threats with our EDR (Endpoint Detection and Response) and XDR (Extended Detection and Response) solutions. Our services offer comprehensive visibility and protection across endpoint, network, and cloud environments. Leverage artificial intelligence and machine learning to identify and mitigate cyber threats. Stay ahead of attackers with our proactive and integrated approach to security.</p>
                            </div>
                            <div className="service_pills">
                                <ul>
                                    <li>CrowdStrike Falcon</li>
                                    <li>Carbon Black</li>
                                    <li>Sentinel One</li>
                                    <li>Microsoft Defender for Endpoint</li>
                                    <li>Palo Alto Networks Cortex XDR</li>
                                    <li>Sophos Intercept X</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
};

export default ServicesSectionTwo;
